apiVersion: autoscaling/v1

kind: Scale

metadata:
  annotations:
    name: Kubernetes-Engine-Starter
    namespace: default

spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1
    kind: Deploy
    name: Kubernetes-Engine-Starter
  targetCPUUtilizationPercentage: 1
