apiVersion: v1

kind: Service

metadata:
  name: Kubernetes-Engine-Starter
  labels:
    app: Kubernetes-Engine-Starter

spec:
  selector:
    app: Kubernetes-Engine-Starter
  ports:
    - port: 3000
      protocol: TCP
      nodePort: 3001
  type: LoadBalancer
